<a href="https://colab.research.google.com/github/Fermu25/Cursos/blob/main/Tutorial_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://www.pythoncentral.io/wp-content/uploads/2021/07/c6h7rok9c2v31.jpg" align = "center" >


<font color = 'blue' size = 8>
Tutorial Pandas

<font size=4>
En este Notebook se aborda el uso de la paqueteria Pandas y su utilidad en diversas aplicaciones.

<font color = 'Black' size = 5>
1.- ¿Por qué Pandas?

<font size=4>

Pandas es un herramienta para manipulación y análisis de datos de código abierto, rápida, poderosa, flexible y fácil de utilizar, construida sobre el lenguaje de programación Python.\
Es de uso común en la ciencia de datos y la inteligencia artificial debido a las ventajas y facilidades que proporciona para cargar, preparar, manipular, modelar y analizar datos.

<font size=4>
Algunas características que hacen útil a Pandas son:

<font size=4>
    
1.- Estructuras de datos similares a matrices ($DataFrame$).\
2.- DataFrames similares a los de otros lenguajes de programación.\
3.- Básicamente, los DataFrames son equivalentes a una tabla.\
4.- Los datos en las columnas deben ser del mismo tipo, pero los datos en renglones pueden variar.\
5.- Altamente flexible para tomar datos de múltiples fuentes.

<font size=4> Cualquier cosa que quieras saber de esta biblioteca en el futuro lo puedes encontrar [aquí](https://pandas.pydata.org/docs/user_guide/index.html)

<font color = 'Black' size = 5>
2.- DataFrames (DF)

<font size=4>
Importamos la paquetería Pandas:

In [3]:
import pandas as pd

<font size=4> Para este ejemplo se utilizó la base de datos **Superconductivty Data Data Set** del repositorio:

[UCI Machine Learning Repository: Superconductivty Data Data Set ](https://archive.ics.uci.edu/ml/datasets/Superconductivty+Data)

<font size=4>
Hay dos archivos:

(1) train.csv: contiene 81 características extraídas de 21263 superconductores junto con la temperatura crítica en la columna 82,


(2) unique_m.csv: contiene la fórmula química dividida para todos los 21263 superconductores del archivo  train.csv



Las dos últimas columnas tienen la temperatura crítica y la fórmula química.
    
**El objetivo de este trabajo fue es predecir la temperatura crítica en función de las características extraídas.**

<font size=4> Levantamos el archivo CSV con pandas:

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_csv('/content/drive/MyDrive/archivos/train.csv')

#Mostramos el DataFrame
df

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                       4         88.944468             57.862692   
1                       5         92.729214             58.518416   
2                       4         88.944468             57.885242   
3                       4         88.944468             57.873967   
4                       4         88.944468             57.840143   
...                   ...               ...                   ...   
21258                   4        106.957877             53.095769   
21259                   5         92.266740             49.021367   
21260                   2         99.663190             95.609104   
21261                   2         99.663190             97.095602   
21262                   3         87.468333             86.858500   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0              66.361592              36.116612             1.181795   
1              73.132787              36.396602             1.449309   
2              66.361592              36.122509             1.181795   
3              66.361592              36.119560             1.181795   
4              66.361592              36.110716             1.181795   
...                  ...                    ...                  ...   
21258          82.515384              43.135565             1.177145   
21259          64.812662              32.867748             1.323287   
21260          99.433882              95.464320             0.690847   
21261          99.433882              96.901083             0.690847   
21262          82.555758              80.458722             1.041270   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                     1.062396          122.90607              31.794921   
1                     1.057755          122.90607              36.161939   
2                     0.975980          122.90607              35.741099   
3                     1.022291          122.90607              33.768010   
4                     1.129224          122.90607              27.848743   
...                        ...                ...                    ...   
21258                 1.254119          146.88130              15.504479   
21259                 1.571630          188.38390               7.353333   
21260                 0.530198           13.51362              53.041104   
21261                 0.640883           13.51362              31.115202   
21262                 0.895229           71.75500              43.144000   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
0            51.968828  ...          2.257143       2.213364   
1            47.094633  ...          2.257143       1.888175   
2            51.968828  ...          2.271429       2.213364   
3            51.968828  ...          2.264286       2.213364   
4            51.968828  ...          2.242857       2.213364   
...                ...  ...               ...            ...   
21258        65.764081  ...          3.555556       3.223710   
21259        69.232655  ...          2.047619       2.168944   
21260         6.756810  ...          4.800000       4.472136   
21261         6.756810  ...          4.690000       4.472136   
21262        29.905282  ...          4.500000       4.762203   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0               2.219783         1.368922             1.066221              1   
1               2.210679         1.557113             1.047221              2   
2               2.232679         1.368922             1.029175              1   
3               2.226222         1.368922             1.048834              1   
4               2.206963         1.368922             1.096052              1   
...                  ...              ...                  ...            ...   
21258           3.519911         1.377820             0.913658  

<font size=4> Podemos verificar las dimensiones del DataFrame con el atributo **.shape** como en los arreglos de Python.

In [5]:
df.shape

(21263, 82)

<font size=4> Observamos que tenemos 21263 superconductores y 82 rasgos (features) de cada uno.

<font size=4> Podemos visualizar los primeros $n$ renglones con el atributo **.head(n)** y los últimos $m$ con **.tail(m)** de la siguiente manera:

In [6]:
n = 10
df.head(n)

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   
5                   4         88.944468             57.795044   
6                   4         88.944468             57.682296   
7                   4         76.517718             57.175142   
8                   4         76.517718             56.808817   
9                   4         76.517718             56.442492   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   
5          66.361592              36.098926             1.181795   
6          66.361592              36.069470             1.181795   
7          59.310096              35.891368             1.197273   
8          59.310096              35.773432             1.197273   
9          59.310096              35.655884             1.197273   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   
5                 1.225203          122.90607              20.687458   
6                 1.316857          122.90607              10.765639   
7                 0.943560          122.90607              36.451199   
8                 0.981880          122.90607              34.833160   
9                 1.016495          122.90607              33.215121   

   std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  wtd_gmean_Valence  \
0        51.968828  ...          2.257143       2.213364           2.219783   
1        47.094633  ...          2.257143       1.888175           2.210679   
2        51.968828  ...          2.271429       2.213364           2.232679   
3        51.968828  ...          2.264286       2.213364           2.226222   
4        51.968828  ...          2.242857       2.213364           2.206963   
5        51.968828  ...          2.214286       2.213364           2.181543   
6        51.968828  ...          2.142857       2.213364           2.119268   
7        44.289459  ...          2.271429       2.213364           2.232679   
8        44.289459  ...          2.264286       2.213364           2.226222   
9        44.289459  ...          2.257143       2.213364           2.219783   

   entropy_Valence  wtd_entropy_Valence  range_Valence  wtd_range_Valence  \
0         1.368922             1.066221              1           1.085714   
1         1.557113             1.047221              2           1.128571   
2         1.368922             1.029175              1           1.114286   
3         1.368922             1.048834              1           1.100000   
4         1.368922             1.096052              1           1.057143   
5         1.368922             1.141474              1           1.000000   
6         1.368922             1.194453              1           0.857143   
7         1.368922             1.029175              1           1.114286   
8         1.368922             1.048834              1           1.100000   
9         1.368922             1.066221              1           1.085714   

   std_Valence  wtd_std_Val

In [7]:
m = 5
df.tail(m)

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
21258                   4        106.957877             53.095769   
21259                   5         92.266740             49.021367   
21260                   2         99.663190             95.609104   
21261                   2         99.663190             97.095602   
21262                   3         87.468333             86.858500   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
21258          82.515384              43.135565             1.177145   
21259          64.812662              32.867748             1.323287   
21260          99.433882              95.464320             0.690847   
21261          99.433882              96.901083             0.690847   
21262          82.555758              80.458722             1.041270   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
21258                 1.254119          146.88130              15.504479   
21259                 1.571630          188.38390               7.353333   
21260                 0.530198           13.51362              53.041104   
21261                 0.640883           13.51362              31.115202   
21262                 0.895229           71.75500              43.144000   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
21258        65.764081  ...          3.555556       3.223710   
21259        69.232655  ...          2.047619       2.168944   
21260         6.756810  ...          4.800000       4.472136   
21261         6.756810  ...          4.690000       4.472136   
21262        29.905282  ...          4.500000       4.762203   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
21258           3.519911         1.377820             0.913658              1   
21259           2.038991         1.594167             1.337246              1   
21260           4.781762         0.686962             0.450561              1   
21261           4.665819         0.686962             0.577601              1   
21262           4.242641         1.054920             0.970116              3   

       wtd_range_Valence  std_Valence  wtd_std_Valence  critical_temp  
21258           2.168889     0.433013         0.496904           2.44  
21259           0.904762     0.400000         0.212959         122.10  
21260           3.200000     0.500000         0.400000           1.98  
21261           2.210000     0.500000         0.462493           1.84  
21262           1.800000     1.414214         1.500000          12.80  

[5 rows x 82 columns]

<font size=4> Podemos renombrar una columna en particular utilzando el atributo **.rename()**

In [9]:
df.rename(columns = {"number_of_elements":"numero_de_elementos"}, inplace = True)  #Cambiamos el nombre de la columna "number_of_elements"
                                                                                    #por "numero_de_elementos"

In [10]:
df

numero_de_elementos  mean_atomic_mass  wtd_mean_atomic_mass  \
0                        4         88.944468             57.862692   
1                        5         92.729214             58.518416   
2                        4         88.944468             57.885242   
3                        4         88.944468             57.873967   
4                        4         88.944468             57.840143   
...                    ...               ...                   ...   
21258                    4        106.957877             53.095769   
21259                    5         92.266740             49.021367   
21260                    2         99.663190             95.609104   
21261                    2         99.663190             97.095602   
21262                    3         87.468333             86.858500   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0              66.361592              36.116612             1.181795   
1              73.132787              36.396602             1.449309   
2              66.361592              36.122509             1.181795   
3              66.361592              36.119560             1.181795   
4              66.361592              36.110716             1.181795   
...                  ...                    ...                  ...   
21258          82.515384              43.135565             1.177145   
21259          64.812662              32.867748             1.323287   
21260          99.433882              95.464320             0.690847   
21261          99.433882              96.901083             0.690847   
21262          82.555758              80.458722             1.041270   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                     1.062396          122.90607              31.794921   
1                     1.057755          122.90607              36.161939   
2                     0.975980          122.90607              35.741099   
3                     1.022291          122.90607              33.768010   
4                     1.129224          122.90607              27.848743   
...                        ...                ...                    ...   
21258                 1.254119          146.88130              15.504479   
21259                 1.571630          188.38390               7.353333   
21260                 0.530198           13.51362              53.041104   
21261                 0.640883           13.51362              31.115202   
21262                 0.895229           71.75500              43.144000   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
0            51.968828  ...          2.257143       2.213364   
1            47.094633  ...          2.257143       1.888175   
2            51.968828  ...          2.271429       2.213364   
3            51.968828  ...          2.264286       2.213364   
4            51.968828  ...          2.242857       2.213364   
...                ...  ...               ...            ...   
21258        65.764081  ...          3.555556       3.223710   
21259        69.232655  ...          2.047619       2.168944   
21260         6.756810  ...          4.800000       4.472136   
21261         6.756810  ...          4.690000       4.472136   
21262        29.905282  ...          4.500000       4.762203   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0               2.219783         1.368922             1.066221              1   
1               2.210679         1.557113             1.047221              2   
2               2.232679         1.368922             1.029175              1   
3               2.226222         1.368922             1.048834              1   
4               2.206963         1.368922             1.096052              1   
...                  ...              ...                  ...            ...   
21258           3.519911         1.377820           

<font size=4> Podemos acceder a información de las columnas del dataframe mediante el atributo **df.column_name** o mediante la instrucción **df['column_name']**

In [11]:
#Utilizamos cada uno de los comandos:

df.numero_de_elementos

0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

In [12]:
df["numero_de_elementos"]

0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

<font size=4> Podemos extraer información de un renglón específico del $DataFrame$  (index) mediante **series** con el atributo **.loc[ ]**:

In [13]:
df.loc[524]  #Utilizamos el atributo .loc()

numero_de_elementos       4.000000
mean_atomic_mass         96.032850
wtd_mean_atomic_mass     58.347829
gmean_atomic_mass        69.515930
wtd_gmean_atomic_mass    37.476574
                           ...    
range_Valence             1.000000
wtd_range_Valence         0.816101
std_Valence               0.433013
wtd_std_Valence           0.269624
critical_temp            85.000000
Name: 524, Length: 82, dtype: float64

<font size=4> Se puede acceder a información en particular utilizando los métodos previos, si por ejemplo queremos obtener la temperatura crítica del superconductor 524:

In [14]:
df['critical_temp'][524]

np.float64(85.0)

<font size=4> En pandas se utilizan también los **operadores de acceso** como el atributo **.iloc[]** que basa su operación en la enumeración de renglones y columnas de Python

<font size=4> Si por ejemplo buscamos la información del superconductor **i-ésimo**, entonces utilizamos **df.iloc[ i ]** el cual obtiene la información del renglón **i-esimo**.

In [15]:
df.iloc[524]

numero_de_elementos       4.000000
mean_atomic_mass         96.032850
wtd_mean_atomic_mass     58.347829
gmean_atomic_mass        69.515930
wtd_gmean_atomic_mass    37.476574
                           ...    
range_Valence             1.000000
wtd_range_Valence         0.816101
std_Valence               0.433013
wtd_std_Valence           0.269624
critical_temp            85.000000
Name: 524, Length: 82, dtype: float64

<font size=4> Si queremos obtener el numero de elementos (columna 0) de todos los superconductores:

In [16]:
df.iloc[:, 0]

0        4
1        5
2        4
3        4
4        4
        ..
21258    4
21259    5
21260    2
21261    2
21262    3
Name: numero_de_elementos, Length: 21263, dtype: int64

<font size=4> Si queremos obtener el número de elementos y su temperatura crítica de los superconductores 0 y 524:

In [17]:
df.iloc[ [0,524],  [0,81] ]

numero_de_elementos  critical_temp
0                      4           29.0
524                    4           85.0

<font size=4> Como se puede observar, el atributo **.iloc[]** utiliza el índice o posición del superconductor (los renglones en este caso) o las columnas para operar. De distinta manera, **.loc[]** basa su operación en el nombre del índice de los datos, no en su posición o enumeración de Python:

<font size=4> Si queremos obtener el numero de elementos en el superconductor 524:

In [18]:
df.loc[524, 'numero_de_elementos']

np.int64(4)

<font size=4> Si quieremos obtener el numero de elementos de los superconductores 524 y 342 por ejemplo:

In [19]:
df.loc[[524, 342], 'numero_de_elementos']

524    4
342    4
Name: numero_de_elementos, dtype: int64

<font size=4> Si quieremos obtener el numero de elementos (columna 0) y temperatura crítica (columna 85) de cada uno de los superconductores:

In [20]:
df.loc[:, ['numero_de_elementos', "critical_temp"]]

numero_de_elementos  critical_temp
0                        4          29.00
1                        5          26.00
2                        4          19.00
3                        4          22.00
4                        4          23.00
...                    ...            ...
21258                    4           2.44
21259                    5         122.10
21260                    2           1.98
21261                    2           1.84
21262                    3          12.80

[21263 rows x 2 columns]

<font size=4> Pandas también puede utilizar **operadores lógicos** como **==**, **<** y **>**.

<font size=4> Si queremos obtener los superconductores con temperatura crítica iguala 85 K hacemos lo siguiente:

In [21]:
df.loc[df.critical_temp == 85]

numero_de_elementos  mean_atomic_mass  wtd_mean_atomic_mass  \
44                       4         90.278600             73.212800   
96                       4         95.450680             54.158394   
215                      5         66.551958             50.924927   
321                      5         80.180280             57.332108   
390                      5         72.894330             51.196194   
...                    ...               ...                   ...   
9578                     5         88.936744             53.011884   
9580                     5         88.936744             53.582250   
9867                     4         93.530600             56.767696   
10107                    5        101.732610             55.559607   
19619                    9        106.879678             53.689115   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
44             66.989987              52.218860             1.178060   
96             69.272696              34.530877             1.161763   
215            50.697784              34.662920             1.383686   
321            58.417634              38.405882             1.357245   
390            59.223421              34.901514             1.447756   
...                  ...                    ...                  ...   
9578           70.358975              35.592933             1.445824   
9580           70.358975              35.684215             1.445824   
9867           68.451761              36.660901             1.168103   
10107          75.894063              37.806460             1.394166   
19619          81.893123              34.718865             1.983797   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
44                    1.268599          128.24260              22.132267   
96                    1.347089          148.93092              10.475629   
215                   1.328146          121.32760              20.856521   
321                   1.440164          135.96460              18.660692   
390                   1.318357          121.32760              20.840307   
...                        ...                ...                    ...   
9578                  1.419545          122.90607              17.129295   
9580                  1.421498          122.90607              18.405824   
9867                  1.339049          141.25060              12.113741   
10107                 1.533141          184.59060              13.028167   
19619                 1.825950          192.98100              14.106655   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
44           53.286096  ...          2.133333       2.213364   
96           58.973428  ...          2.071429       2.213364   
215          43.907216  ...          2.092951       2.352158   
321          55.008390  ...          2.384615       2.701920   
390          39.834730  ...          2.076864       2.168944   
...                ...  ...               ...            ...   
9578         46.482335  ...          2.077399       2.352158   
9580         46.482335  ...          2.076982       2.352158   
9867         56.763654  ...          2.081144       2.213364   
10107        63.741719  ...          2.150000       2.297397   
19619        68.244756  ...          2.108462       2.534794   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
44              2.111100         1.368922             1.354710              1   
96              2.058771         1.368922             1.162020              1   
215             2.076815         1.589027             1.280480              1   
321             2.245314         1.494365             1.493310              4   
390             2.063313         1.594167             1.223190              1   
...                  ...              ...                  ...            ...   
9578            2.063761         1.589027           

<font size=4> Si queremos obtener los superconductores con temperatura crítica menor a 85 K hacemos lo siguiente:

In [22]:
df.loc[df.critical_temp < 85]

numero_de_elementos  mean_atomic_mass  wtd_mean_atomic_mass  \
0                        4         88.944468             57.862692   
1                        5         92.729214             58.518416   
2                        4         88.944468             57.885242   
3                        4         88.944468             57.873967   
4                        4         88.944468             57.840143   
...                    ...               ...                   ...   
21257                    3         89.389833             89.389833   
21258                    4        106.957877             53.095769   
21260                    2         99.663190             95.609104   
21261                    2         99.663190             97.095602   
21262                    3         87.468333             86.858500   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0              66.361592              36.116612             1.181795   
1              73.132787              36.396602             1.449309   
2              66.361592              36.122509             1.181795   
3              66.361592              36.119560             1.181795   
4              66.361592              36.110716             1.181795   
...                  ...                    ...                  ...   
21257          63.694713              63.694713             0.782574   
21258          82.515384              43.135565             1.177145   
21260          99.433882              95.464320             0.690847   
21261          99.433882              96.901083             0.690847   
21262          82.555758              80.458722             1.041270   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                     1.062396          122.90607              31.794921   
1                     1.057755          122.90607              36.161939   
2                     0.975980          122.90607              35.741099   
3                     1.022291          122.90607              33.768010   
4                     1.129224          122.90607              27.848743   
...                        ...                ...                    ...   
21257                 0.782574          164.13150              54.710500   
21258                 1.254119          146.88130              15.504479   
21260                 0.530198           13.51362              53.041104   
21261                 0.640883           13.51362              31.115202   
21262                 0.895229           71.75500              43.144000   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
0            51.968828  ...          2.257143       2.213364   
1            47.094633  ...          2.257143       1.888175   
2            51.968828  ...          2.271429       2.213364   
3            51.968828  ...          2.264286       2.213364   
4            51.968828  ...          2.242857       2.213364   
...                ...  ...               ...            ...   
21257        73.156893  ...          4.666667       4.578857   
21258        65.764081  ...          3.555556       3.223710   
21260         6.756810  ...          4.800000       4.472136   
21261         6.756810  ...          4.690000       4.472136   
21262        29.905282  ...          4.500000       4.762203   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0               2.219783         1.368922             1.066221              1   
1               2.210679         1.557113             1.047221              2   
2               2.232679         1.368922             1.029175              1   
3               2.226222         1.368922             1.048834              1   
4               2.206963         1.368922             1.096052              1   
...                  ...              ...                  ...            ...   
21257           4.578857         1.078992           

<font size=4> Si queremos los superconductores con temperatura crítica de 83 o de 85 K

In [23]:
df.loc[df.critical_temp.isin( [83, 85] )]

numero_de_elementos  mean_atomic_mass  wtd_mean_atomic_mass  \
44                       4         90.278600             73.212800   
96                       4         95.450680             54.158394   
215                      5         66.551958             50.924927   
321                      5         80.180280             57.332108   
390                      5         72.894330             51.196194   
...                    ...               ...                   ...   
9890                     5         74.231650             51.439672   
10107                    5        101.732610             55.559607   
17051                    5         83.244760             67.805676   
19389                    6         78.610876             80.707050   
19619                    9        106.879678             53.689115   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
44             66.989987              52.218860             1.178060   
96             69.272696              34.530877             1.161763   
215            50.697784              34.662920             1.383686   
321            58.417634              38.405882             1.357245   
390            59.223421              34.901514             1.447756   
...                  ...                    ...                  ...   
9890           60.515221              35.085017             1.453747   
10107          75.894063              37.806460             1.394166   
17051          59.506081              38.620521             1.311510   
19389          59.971380              67.005030             1.582322   
19619          81.893123              34.718865             1.983797   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
44                    1.268599          128.24260              22.132267   
96                    1.347089          148.93092              10.475629   
215                   1.328146          121.32760              20.856521   
321                   1.440164          135.96460              18.660692   
390                   1.318357          121.32760              20.840307   
...                        ...                ...                    ...   
9890                  1.304014          121.32760              21.127838   
10107                 1.533141          184.59060              13.028167   
17051                 1.174211          192.98100              38.438876   
19389                 1.273116          122.90607              35.715388   
19619                 1.825950          192.98100              14.106655   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
44           53.286096  ...          2.133333       2.213364   
96           58.973428  ...          2.071429       2.213364   
215          43.907216  ...          2.092951       2.352158   
321          55.008390  ...          2.384615       2.701920   
390          39.834730  ...          2.076864       2.168944   
...                ...  ...               ...            ...   
9890         39.445875  ...          2.077340       2.168944   
10107        63.741719  ...          2.150000       2.297397   
17051        67.233835  ...          2.572727       2.402249   
19389        48.307597  ...          2.185714       2.449490   
19619        68.244756  ...          2.108462       2.534794   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
44              2.111100         1.368922             1.354710              1   
96              2.058771         1.368922             1.162020              1   
215             2.076815         1.589027             1.280480              1   
321             2.245314         1.494365             1.493310              4   
390             2.063313         1.594167             1.223190              1   
...                  ...              ...                  ...            ...   
9890            2.063711         1.594167           

<font size=4> Si queremos identificar todas las posiciones en el dataframe que tienen un valor vacío o **"NaN"**

In [27]:
df.loc[df.critical_temp.isnull()].shape

(0, 82)

In [28]:
#df.loc[df.critical_temp.isnull()].shape
df.loc[df.critical_temp.notnull()].shape

(21263, 82)

<font size=4> Pandas también puede calcular promedios, desviación estándar, etc. y otras funciones útiles, por ejemplo:

<font size=4> El atributo **.describe()** nos da la siguiente información de cada una de las columnas del dataframe:

In [29]:
df.describe()

numero_de_elementos  mean_atomic_mass  wtd_mean_atomic_mass  \
count         21263.000000      21263.000000          21263.000000   
mean              4.115224         87.557631             72.988310   
std               1.439295         29.676497             33.490406   
min               1.000000          6.941000              6.423452   
25%               3.000000         72.458076             52.143839   
50%               4.000000         84.922750             60.696571   
75%               5.000000        100.404410             86.103540   
max               9.000000        208.980400            208.980400   

       gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
count       21263.000000           21263.000000         21263.000000   
mean           71.290627              58.539916             1.165608   
std            31.030272              36.651067             0.364930   
min             5.320573               1.960849             0.000000   
25%            58.041225              35.248990             0.966676   
50%            66.361592              39.918385             1.199541   
75%            78.116681              73.113234             1.444537   
max           208.980400             208.980400             1.983797   

       wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
count             21263.000000       21263.000000           21263.000000   
mean                  1.063884         115.601251              33.225218   
std                   0.401423          54.626887              26.967752   
min                   0.000000           0.000000               0.000000   
25%                   0.775363          78.512902              16.824174   
50%                   1.146783         122.906070              26.636008   
75%                   1.359418         154.119320              38.356908   
max                   1.958203         207.972460             205.589910   

       std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  \
count     21263.000000  ...      21263.000000   21263.000000   
mean         44.391893  ...          3.153127       3.056536   
std          20.035430  ...          1.191249       1.046257   
min           0.000000  ...          1.000000       1.000000   
25%          32.890369  ...          2.116732       2.279705   
50%          45.123500  ...          2.618182       2.615321   
75%          59.322812  ...          4.026201       3.727919   
max         101.019700  ...          7.000000       7.000000   

       wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
count       21263.000000     21263.000000         21263.000000   21263.000000   
mean            3.055885         1.295682             1.052841       2.041010   
std             1.174815         0.393155             0.380291       1.242345   
min             1.000000         0.000000             0.000000       0.000000   
25%             2.091251         1.060857             0.775678       1.000000   
50%             2.434057         1.368922             1.166532       2.000000   
75%             3.914868         1.589027             1.330801       3.000000   
max             7.000000         2.141963             1.949739       6.000000   

       wtd_range_Valence   std_Valence  wtd_std_Valence  critical_temp  
count       21263.000000  21263.000000     21263.000000   21263.000000  
mean            1.483007      0.839342         0.673987      34.421219  
std             0.978176      0.484676         0.455580      34.254362  
min             0.000000      0.000000         0.000000       0.000210  
25%             0.921454      0.451754         0.306892       5.365000  
50%             1.063077      0.800000         0.500000      20.000000  
75%             1.918400      1.200000         1.020436      63.000000  
max             6.992200      3.000000         3.000000     185.000000  

[8 rows x 82 columns]

<font size = 4> Si queremos sólo la información de la temperatura crítica:

In [30]:
df.critical_temp.describe()

count    21263.000000
mean        34.421219
std         34.254362
min          0.000210
25%          5.365000
50%         20.000000
75%         63.000000
max        185.000000
Name: critical_temp, dtype: float64

<font size=4> El atributo **.mean()** nos regresa el promedio, en este caso, de cada columna:

In [31]:
#df.critical_temp.mean()

df.mean()

numero_de_elementos       4.115224
mean_atomic_mass         87.557631
wtd_mean_atomic_mass     72.988310
gmean_atomic_mass        71.290627
wtd_gmean_atomic_mass    58.539916
                           ...    
range_Valence             2.041010
wtd_range_Valence         1.483007
std_Valence               0.839342
wtd_std_Valence           0.673987
critical_temp            34.421219
Length: 82, dtype: float64

<font color = 'white' size = 5>
3.- Operaciones con DataFrames

<font size=4> El atributo **.unique()** nos regresa los valores posibles que puede tomar un elemento sin repetir:

In [32]:
df.critical_temp.unique()

array([ 29.   ,  26.   ,  19.   , ...,   1.445,   1.165, 122.1  ])

<font size = 5> Por otro lado, el archivo **unique_m.csv** contiene la composición por elemento de cada uno de los superconductores así como su fórmula.

In [33]:
df_2 = pd.read_csv('/content/drive/MyDrive/archivos/unique_m.csv')
df_2

H  He   Li   Be    B    C    N     O    F  Ne  ...   Au   Hg   Tl  \
0      0.0   0  0.0  0.0  0.0  0.0  0.0   4.0  0.0   0  ...  0.0  0.0  0.0   
1      0.0   0  0.0  0.0  0.0  0.0  0.0   4.0  0.0   0  ...  0.0  0.0  0.0   
2      0.0   0  0.0  0.0  0.0  0.0  0.0   4.0  0.0   0  ...  0.0  0.0  0.0   
3      0.0   0  0.0  0.0  0.0  0.0  0.0   4.0  0.0   0  ...  0.0  0.0  0.0   
4      0.0   0  0.0  0.0  0.0  0.0  0.0   4.0  0.0   0  ...  0.0  0.0  0.0   
...    ...  ..  ...  ...  ...  ...  ...   ...  ...  ..  ...  ...  ...  ...   
21258  0.0   0  0.0  0.0  0.0  0.0  0.0   0.0  0.0   0  ...  0.0  0.0  0.0   
21259  0.0   0  0.0  0.0  0.0  0.0  0.0  11.0  0.0   0  ...  0.0  0.0  1.0   
21260  0.0   0  0.0  0.0  0.0  0.0  0.0   0.0  0.0   0  ...  0.0  0.0  0.0   
21261  0.0   0  0.0  0.0  0.0  0.0  0.0   0.0  0.0   0  ...  0.0  0.0  0.0   
21262  0.0   0  0.0  0.0  0.0  0.0  0.0   0.0  0.0   0  ...  0.0  0.0  0.0   

        Pb   Bi  Po  At  Rn  critical_temp                material  
0      0.0  0.0   0   0   0          29.00         Ba0.2La1.8Cu1O4  
1      0.0  0.0   0   0   0          26.00  Ba0.1La1.9Ag0.1Cu0.9O4  
2      0.0  0.0   0   0   0          19.00         Ba0.1La1.9Cu1O4  
3      0.0  0.0   0   0   0          22.00       Ba0.15La1.85Cu1O4  
4      0.0  0.0   0   0   0          23.00         Ba0.3La1.7Cu1O4  
...    ...  ...  ..  ..  ..            ...                     ...  
21258  0.0  0.0   0   0   0           2.44      Tm0.84Lu0.16Fe3Si5  
21259  0.0  0.0   0   0   0         122.10         Tl1Ba2Ca3Cu4O11  
21260  0.0  0.0   0   0   0           1.98              Nb0.8Pd0.2  
21261  0.0  0.0   0   0   0           1.84            Nb0.69Pd0.31  
21262  0.0  0.0   0   0   0          12.80           Fe1Se0.2Te0.8  

[21263 rows x 88 columns]

<font size=4> Si queremos agregar a nuestro dataframe original la columna **material** que aparece en este nuevo archivo, hacemos lo siguiente:

In [ ]:
df["compuesto"] = df_2["material"]

In [ ]:
df

numero_de_elementos  ...               compuesto
0                        4  ...         Ba0.2La1.8Cu1O4
1                        5  ...  Ba0.1La1.9Ag0.1Cu0.9O4
2                        4  ...         Ba0.1La1.9Cu1O4
3                        4  ...       Ba0.15La1.85Cu1O4
4                        4  ...         Ba0.3La1.7Cu1O4
...                    ...  ...                     ...
21258                    4  ...      Tm0.84Lu0.16Fe3Si5
21259                    5  ...         Tl1Ba2Ca3Cu4O11
21260                    2  ...              Nb0.8Pd0.2
21261                    2  ...            Nb0.69Pd0.31
21262                    3  ...           Fe1Se0.2Te0.8

[21263 rows x 83 columns]

<font size=4> Observamos que se agregó la columna **material** ahora con el nombre **compuesto**.

<font color = 'white' size = 5>
4.- Removiendo Null values

<font size=4> Estaremos utilizando el atributo **dataframe.dropna()** cuya documentación puedes consultar [aquí](https://pandas.pydata.org/docs/user_guide/index.html)

<font size=4> Definimos un dataframe de prueba que contenga Null values

In [34]:
df = pd.DataFrame({
    'colA':[None, False, False, True],
    'colB': [None, 2, None, 4],
    'colC': [None, 'b', 'c', 'd'],
    'colD': [None, 2.0, 3.0, 4.0],
    })

print(df)

    colA  colB  colC  colD
0   None   NaN  None   NaN
1  False   2.0     b   2.0
2  False   NaN     c   3.0
3   True   4.0     d   4.0


<font size=4> Si quieremos eliminar todos los **renglones** con al menos un valor **NaN** hacemos lo siguiente:

In [35]:
df_rows = df.dropna()

#Imprimimos el DF
df_rows

colA  colB colC  colD
1  False   2.0    b   2.0
3   True   4.0    d   4.0

<font size=4> Si quieremos eliminar los **renglones** que **únicamente** tengan valores **NaN** hacemos lo siguiente:

In [36]:
df_u_rows = df.dropna(how='all')

#Imprimimos el DF
df_u_rows

colA  colB colC  colD
1  False   2.0    b   2.0
2  False   NaN    c   3.0
3   True   4.0    d   4.0

<font size=4> Si quieremos eliminar los **renglones** que tengan valores **NaN**, **únicamente** en ciertos renglones,  hacemos lo siguiente:

In [37]:
df_just_some_columns = df.dropna(subset=['colA', 'colC'])

#Imprimimos el DF
df_just_some_columns

colA  colB colC  colD
1  False   2.0    b   2.0
2  False   NaN    c   3.0
3   True   4.0    d   4.0

<font size=4> En este último caso, definimos en el subconjunto **subset** el nombre de las columnas donde queremos aplicar la eliminación de valores *NaN*.

<font size=4> En algunas ocasiones no queremos eliminar los datos de nuestro dataframe, y en su lugar queremos **reemplazar** los valores **NaN** por 0 u otro valor.

<font size=4> Para este propósito, utilizaremos el atributo **df.fillna()**. Cuya documentación puedes encontrar [aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

In [38]:
df.fillna(0)

colA  colB colC  colD
0      0   0.0    0   0.0
1  False   2.0    b   2.0
2  False   0.0    c   3.0
3   True   4.0    d   4.0

**Ejercicio 6**
Utilizando el archivo CSV unique_m.csv, determina el número de compuestos que tienen hidrógeno en su composición y que tienen una temperatura crítica inferior a los 100 Kelvin.

In [40]:
df= pd.read_csv('/content/drive/MyDrive/archivos/unique_m.csv')
df.describe()

H       He            Li            Be             B  \
count  21263.000000  21263.0  21263.000000  21263.000000  21263.000000   
mean       0.017685      0.0      0.012125      0.034638      0.142594   
std        0.267220      0.0      0.129552      0.848541      1.044486   
min        0.000000      0.0      0.000000      0.000000      0.000000   
25%        0.000000      0.0      0.000000      0.000000      0.000000   
50%        0.000000      0.0      0.000000      0.000000      0.000000   
75%        0.000000      0.0      0.000000      0.000000      0.000000   
max       14.000000      0.0      3.000000     40.000000    105.000000   

                  C             N             O             F       Ne  ...  \
count  21263.000000  21263.000000  21263.000000  21263.000000  21263.0  ...   
mean       0.384968      0.013284      3.009129      0.014874      0.0  ...   
std        4.408032      0.150427      3.811649      0.132119      0.0  ...   
min        0.000000      0.000000      0.000000      0.000000      0.0  ...   
25%        0.000000      0.000000      0.000000      0.000000      0.0  ...   
50%        0.000000      0.000000      1.000000      0.000000      0.0  ...   
75%        0.000000      0.000000      6.800000      0.000000      0.0  ...   
max      120.000000     12.800000     66.000000      4.000000      0.0  ...   

                 Pt            Au            Hg            Tl            Pb  \
count  21263.000000  21263.000000  21263.000000  21263.000000  21263.000000   
mean       0.034108      0.020535      0.036663      0.047954      0.042461   
std        0.307888      0.717975      0.205846      0.272298      0.274365   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        5.800000     64.000000      8.000000      7.000000     19.000000   

                 Bi       Po       At       Rn  critical_temp  
count  21263.000000  21263.0  21263.0  21263.0   21263.000000  
mean       0.201009      0.0      0.0      0.0      34.421219  
std        0.655927      0.0      0.0      0.0      34.254362  
min        0.000000      0.0      0.0      0.0       0.000210  
25%        0.000000      0.0      0.0      0.0       5.365000  
50%        0.000000      0.0      0.0      0.0      20.000000  
75%        0.000000      0.0      0.0      0.0      63.000000  
max       14.000000      0.0      0.0      0.0     185.000000  

[8 rows x 87 columns]

In [44]:
df1 = df[[ 'H', 'critical_temp']]
df1

H  critical_temp
0      0.0          29.00
1      0.0          26.00
2      0.0          19.00
3      0.0          22.00
4      0.0          23.00
...    ...            ...
21258  0.0           2.44
21259  0.0         122.10
21260  0.0           1.98
21261  0.0           1.84
21262  0.0          12.80

[21263 rows x 2 columns]

In [77]:
Hidrogeno = df1['H'] > 0

Temp = df1['critical_temp'] < 100

filtro = df1[Hidrogeno & Temp]

d2 = len(filtro)

print(d2)

296


*Ejercicio 7*
¿Cuál es el promedio de la fracción de composición de hidrógeno en los compuestos obtenidos en el ejercicio 6 y qué valores tienen los cuartiles (25%, 50%, 75%) en su temperatura crítica?

In [88]:
promedio=filtro.iloc[:,0].mean()
cuartiles=filtro.iloc[:,1].quantile([0.25,0.5,0.75])
print(promedio)
cuartiles

1.256847972972973


0.25     4.37125
0.50    13.70000
0.75    45.07500
Name: critical_temp, dtype: float64